### ISSUE TITLE
Confusion in the description of Tests 1 and 2 in the Test Assurance Activities for SFR FCS_CKM.4 in HCD SD v1.0

### ISSUE THREAD

**Issue by ansukert** [HCD-iTC/HCD-IT#19]
An issue from Masatoshi Kawashima Information Technology Security Center

HCD SD Version 1.0
**Section of HCD cPP/HCD SD in question (reference to SFR or subchapter in the HCD cPP or HCD SD):
Section 2.2.4. FCS_CKM.4 Cryptographic key destruction, Section 2.2.4.4 Tests”

**Issue:**
As to tests of FCS_CKM.4, I understand that Test 1 is applied to keys held in volatile memory, and Test 2 through 4 are applied to keys held in nonvolatile memory.

The paragraph just before Test 2 of Section 2.2.4.4 of HCD SD seems to be confusing. The first sentence beginning with “The following tests apply …” seems to describe about Test 1. Is the word “following” a misentry of “above”? But the phrase beginning with “since the TOE in this instance …” seems to describe the case that non-volatile memory is selected.

The second sentence beginning with “In selection non-volatile storage), …” seems to describe the case that volatile memory is selected , and the last sentence beginning with “For selection volatile memory),…” seems to describe the case that non-volatile memory is selected.

**Proposed Resolution(if any):**

I think the following is adequate for the paragraph;

“The above tests apply to only to selection volatile memory, since the TOE in this instance has more visibility into what is happening within the underlying plat form (e.g., a logical view of the media). In selection volatile storage, the TOE has no visibility into inner workings and completely relies on the underlying platform, so there is no reason to test the TOE beyond test 1. For selection non-volatile memory, the following tests are used to determine the TOE is able to request the platform to overwrite the key with a TOE supplied pattern.”

**Comment by Ryuichiro-Ohya-FX** [comment]
As I mentioned in the previous HIT meeting, the modification proposed by ITSC is as shown in the picture. Let me make this note for making sure.

![aaa](https://github.com/HCD-iTC/HCD-IT/assets/65152797/ca85959f-d1a8-433e-8131-a5c6e36a9e7e)

**Comment by gcolunga** [comment]
This issue is addressed by the following TD: 

- HCD0007

The TD above is located at the following location: 

- https://github.com/HCD-iTC/HCD-iTC-Template/tree/Working/TD
