### ISSUE TITLE
Clarification of Test Requirements and Context of FPT_TST_EXT.1

### ISSUE THREAD

**Issue by onuroztkn** [HCD-iTC/HCD-IT#22]
**Observation:**
cPP Section 5.8.4. "FPT_TST_EXT.1 Extended: TSF testing" has the following two paragraphs under Application Note, which has minor consistency among each other:

> **Application Note:**
> Power-on self-tests may take place before the TSF is operational, in which case this SFR can be
> satisfied by verifying the TSF image by digital signature as specified in FCS_COP.1/SigGen, or by
> hash specified in FCS_COP.1/Hash.
> 
> Self-test is intended to detect malfunctions which may compromise the TSF. Since the integrity of
> the firmware/software is guaranteed by FPT_SBT_EXT, the function for FPT_TST_EXT should
> address the malfunction detection like DRBG self-test defined in ISO/IEC 18031:2011.

Is it sufficient to only run an integrity test (no other tests) on start-up/power on?

**Suggestions:**
1. If integrity of TOE image is sufficient to meet the intent of FPT_TST_EXT.1, then the SFR should be reworded as:
_FPT_TST_EXT.1.1 The TSF shall run **an integrity test** on TOE software/firmware during initial start-up (and power on) to
demonstrate the correct operation of the TSF._

2. If testing of TOE image integrity is not in scope of FPT_TST_EXT.1 (as it's covered under FPT_SBT_EXT.1 as per Application Note provided above), the testing requirement in the SD should be updated accordingly.

_Note: The Application Note was initially changed as a result of the following Issue raised against the draft cPP: https://github.com/HCD-iTC/HCD-iTC-Template/issues/261_

**Comment by Ryuichiro-Ohya-FX** [comment]
In my understanding, the current FPT_TST_EXT.1 doesn't include integrity of TOE image in its scope because integrity of TOE image is required by FPT_SBT_EXT.1 at the present.
However, I couldn't identify how we need to modify the testing requirement. The current testing requirement seems applicable even if DRBG self-test is a only function of FPT_TST_EXT.1.

**Comment by ClarkCP** [comment]
It might not include the testing of integrity (which is covered under SBT), the application note for TST suggests that it would be in scope for the SFR:

"Power-on self-tests may take place before the TSF is operational, in **which case this SFR can be satisfied by verifying the TSF image by digital signature** as specified in FCS_COP.1/SigGen, or byhash specified in FCS_COP.1/Hash."

This application note implies that if only an integrity test is run, then that would be sufficient.  Is that the intent?  If not, then the note should be removed and clarification added wrt what is "sufficient" (i.e. crypto functionality, etc.).  

Given that the testing requirement is to "break" the tests, requiring additonal tests might raise other challenges.

**Comment by Ryuichiro-Ohya-FX** [comment]
I understood what you pointed.
Yes, removing the part of Application Note seems reasonable.
And I think we don't need to add another description for this requirement. In my understanding, the current definition of this requirement is leaving a room intentionally for what vendors implement for the purpose of this requirement. If so, I think just removing the part of application note is good enough.

As for evaluation activities, I don’t think we need any changes.

**Comment by onuroztkn** [comment]
Some additional comments:

1. If TOE firmware/software integrity testing is not part of FPT_TST_EXT.1 and therefore Application Note para. 1 needs to be removed for consistency; then I recommend para. 2 to be moved to SD for FPT_TST_EXT.1 under Tests (as it is directly related to Testing).

This is because FPT_TST_EXT.1 SFR and the Assurance Activity requirements in SD (TSS, Guidance Documentation) still refers to all self-tests conducted on the TOE that ensures correct operation of TSF, which theoretically still includes TOE integrity tests. Having the current Para. 2 of the Application Note in PP creates a confusion as if TOE integrity tests should not be part of FPT_TST_EXT.1 and therefore should be excluded completely from TSS and Guidance document requirements as well.

_I believe the intent of FPT_TST_EXT.1 is to list all self-tests (including TOE integrity test), but not test TOE integrity test under FPT_TST_EXT.1 as it is already guaranteed as part of FPT_SBT_EXT.1._

2. At that point, Lab has concerns on testing aspect of FPT_TST_EXT.1 as it is looking for a negative test which excludes TOE integrity self-tests. This limits the testing to either cryptographic library/module (which can be third-party), or possibly low-level testing aspects like memory testing etc. which most likely require debug firmware, customized modules (to trigger a fail) or vendor-generated test tools.

This brings additional concerns: 
a. The test becomes a vendor testing at best, with the evaluator basically verifying vendor testing effort (or doing a code review).
b. The TOE no longer maintains integrity as customized modules are required for testing (testing DRBG failure on the TOE is not easy to achieve without manipulating code). A customized tool/module to show failure has limited assurance on the actual TOE itself.

_Recommendation: Instead of a negative test to prove that TOE does not become operational in case of a failure (for claimed self-tests outside of TOE software/firmware integrity), a similar approach for testing in FPT_TST_EXT.1 in NDcPP can be followed._

**Comment by Ryuichiro-Ohya-FX** [comment]
>  1. If TOE firmware/software integrity testing ..... then I recommend para. 2 to be moved to SD for FPT_TST_EXT.1 under Tests (as it is directly related to Testing).

I'm fine with your recommendation.

> I believe the intent of FPT_TST_EXT.1 is to list all self-tests (including TOE integrity test), but not test TOE integrity test under FPT_TST_EXT.1 as it is already guaranteed as part of FPT_SBT_EXT.1.

Yes, my expectation is the same as yours.

> 2. At that point, Lab has concerns on testing aspect of FPT_TST_EXT.1
> This brings additional concerns:....

They were what the labs in Japan were doing for HCD PP evaluation.

> Recommendation: Instead of a negative test ...., a similar approach for testing in FPT_TST_EXT.1 in NDcPP can be followed.

I'm not sure how it is like. Do you mean the following description of ND SD 2.2e can be applied for HCD cPP as well?
"Although formal compliance is not mandated, the self-tests performed should aim for a level of confidence comparable to:...."

**Comment by onuroztkn** [comment]
> I'm fine with your recommendation.

Thank you. 

For Item 2:
ND SD 2.2e and new ND SD 3.0e both include tests related to verification of correct operation (of self-tests). How to verify correct operation is left to the evaluation lab (positive/negative testing). 

Whereas, current HCD cPP not only excludes TOE software/firmware integrity testing from FPT_TST_EXT.1, but it also mandates a failure (negative) test, which forces the Vendor to alter a module (code change) or requires a vendor generated tool to verify out-of-TOE configuration of a module/component. Again, the concern here is that the evaluator is verifying Vendor testing efforts at this point on a specific part of TOE.

If FPT_TST_EXT.1 already excludes certain self-tests (TOE integrity), then the testing aspect should not force for a negative test. Based on the claims on the ST, the lab should verify power-on self tests occurring on the TOE. The requirement should be similar on how the assurance activities are written on ND SDs.

My recommendation is:
Since TOE firmware/software integrity is tested under FPT_SBT_EXT and it is difficult to break other tests (i.e. memory, CPU, etc.), the negative test requirement should be removed, or/and the test requirement for FPT_TST_EXT should be confirmation that the claimed tests run, as per the NDcPP.

**Comment by Ryuichiro-Ohya-FX** [comment]
Please let me confirm if my understanding is correct.
I attached the files including amended description I made based on my understanding of your recommendation.
Please take a look at them, and check if they are what you expected.

And I think, if the evaluation activities need to be modified, reviewing the modification by HCD iTC including other schemes and labs might be necessary.
[Supporting Document for Hardcopy Devices.docx](https://github.com/HCD-iTC/HCD-IT/files/13656482/Supporting.Document.for.Hardcopy.Devices.docx)
[collaborative Protection Profile for Hardcopy Devices.docx](https://github.com/HCD-iTC/HCD-IT/files/13656483/collaborative.Protection.Profile.for.Hardcopy.Devices.docx)

**Comment by onuroztkn** [comment]
> I attached the files including amended description I made based on my understanding of your recommendation.
> Please take a look at them, and check if they are what you expected.

Thank you, Ohya-san, for drafting these changes through documents.
I find both changes appropriate and I believe that the way the test requirement is proposed now, for FPT_TST_EXT.1, HCD cPP becomes more consistent with the level of assurance ND cPP offers.

I also agree that since this includes modifications to the assurance activities, it should include review/approval from other parties as you mentioned.

**Comment by gcolunga** [comment]
This issue is addressed by the following TD: 

- HCD0009

The TD above is located at the following location: 

- https://github.com/HCD-iTC/HCD-iTC-Template/tree/Working/TD
