### ISSUE TITLE
Modification proposal : tests for FDP_DSK_EXT.1.

### ISSUE THREAD

**Issue by sato1048** [HCD-iTC/HCD-IT#9]
**Issue**
This SFR should be satisfied and certified if encryption of any confidential data will not depend on a user electing to protect that data.

However current test description is limited to perform writing to the storage device with “operating TSFI“ which enforce write process of User documents and Confidential TSF data. Therefore, a functionality which does not have such TSFI and the data cannot be tested and certified even if the TOE function is satisfied with the SFR.
This situation should be corrected. 
For more detail, SWAP and Core dump etc., are written User documents and Confidential TSF data to storage device by system (OS) at any timing as necessary.
SWAP and Core dump etc., doesn’t write any User documents and Confidential TSF data when TSFI is operated.

**Proposal**
If System (OS) write any User documents and Confidential TSF data at any time as necessary, and it doesn’t write any data when TSFI is operated, the evaluator shall verify the ST and KMD as bellow.

1.	Encryption function for Storage device should be confirmed by TSS in the ST.
2.	Encryption function for Storage device written in TSS should be confirmed by KMD.

**Comment by sato1048** [comment]
Proposal from Toshiba Tec for SD

The evaluator shall perform the following tests:
Test 1. Write data to Storage device: Perform writing to the storage device with operating TSFI which enforce write process of User documents and Confidential TSF data.
Or perform writing known data to the storage device by transparent encryption to test transparent encryption function which enforce write process of User documents and Confidential TSF data.

Test 2. Confirm that written data are encrypted: Verify there are no plaintext data present in the
encrypted range written by Test 1; and, verify that the data can be decrypted by proper key and key
material.
All TSFIs or at least representative TSFI for writing User Document Data and Confidential TSF data should be tested by above Test 1 and Test 2.
If these TSFIs are realized by transparent encryption, it is sufficient to verify by calling the transparent encryption function.: It is no need to repeat same tests for all TSFIs.

Please refer to attached document for more detail
[Proposal for No.9 on HIT 20231205.docx](https://github.com/HCD-iTC/HCD-IT/files/13545285/Proposal.for.No.9.on.HIT.20231205.docx)

**Comment by sato1048** [comment]
Alternative proposal from Toshiba Tec for SD

3.1.3.1. TSS
If any User document or Confidential TSF data are potentially transparently encrypted and written to disk via mechanisms other than the operating TSFI, the evaluator shall verify that the TSS identifies those mechanisms and describes at a high level how the associated data are encrypted.  Examples of such mechanisms could include swap files and core dumps.

3.1.3.4. Tests
Test 5. 
[Conditional: If any of User documents or Confidential TSF data are potentially transparently encrypted and written to disk via mechanisms other than the operating TSFI] Using a special tooling that the developer shall provide, the evaluator shall write the known data to the storage through transparently encryption.

Test 6. 
[Conditional: If any of User documents or Confidential TSF data are potentially transparently encrypted and written to disk via mechanisms other than the operating TSFI] Verify that the data written in Test 5 is not in plaintext form; and verify that the data can be decrypted by proper key and key material.

Test 5 and Test 6 should be performed for each mechanism not involving the operating TSFIs described in the TSS.

Please refer to attached document for more detail
[Proposal for No.9 on HIT 20231208 Response2.docx](https://github.com/HCD-iTC/HCD-IT/files/13632467/Proposal.for.No.9.on.HIT.20231208.Response2.docx)

**Comment by sato1048** [comment]
It is agreed in the HIT meeting that TSS and Test in the SD will be modified as follows.


3.1.3.1. TSS
If any User document or Confidential TSF data are transparently encrypted and written to disk via mechanisms other than the operating TSFI, the evaluator shall verify that the TSS identifies those mechanisms and describes at a high level how the associated data are encrypted. The swap files and core dump may potentially contain User document or Confidential TSF data should be considered.

3.1.3.4. Tests
Test 5. 
[Conditional: If any of User documents or Confidential TSF data are transparently encrypted and written to disk via mechanisms other than the operating TSFI] Using a special tooling that the developer shall provide, the evaluator shall write the known data to the storage through transparently encryption.

Test 6. 
[Conditional: If any of User documents or Confidential TSF data are transparently encrypted and written to disk via mechanisms other than the operating TSFI] Verify that the data written in Test 5 is not in plaintext form; and verify that the data can be decrypted by proper key and key material.

Test 5 and Test 6 should be performed for each mechanism not involving the operating TSFIs described in the TSS.

[Proposal for No.9 on HIT 20231212 conclusion.docx](https://github.com/HCD-iTC/HCD-IT/files/13644713/Proposal.for.No.9.on.HIT.20231212.conclusion.docx)

**Comment by gcolunga** [comment]
This issue is addressed by the following TD: 

- HCD0004

The TD above is located at the following location: 

- https://github.com/HCD-iTC/HCD-iTC-Template/tree/Working/TD
